service: pantry-pal-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
